name: Run Jmeter Tests from Config File
on:
  push:
    branches:
      - main
  
jobs:  
  job1-api:
    runs-on: ubuntu-latest
    strategy:
      matrix:
          folder: [DeterAPI1]
          scripts: [script1.sh,script2.sh]
    
    steps:
      # checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2
        
     # - name: Set up AWS CLI
      #  uses: aws-actions/configure-aws-credentials@v1
       # with:
        #  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        #  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         # aws-region: us-east-1


      - name: Run Script
        run: |
          echo "Processing folder: ${{ matrix.folder }}"
          if [ -f "${{ matrix.folder }}/scripts" ]; then
            bash "${{ matrix.folder }}/scripts"
          else
            echo "No script found in ${{ matrix.folder }}"
          fi

  job2-ui:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: [DeterUI]
        scripts: [script1.sh,script2.sh]
    
    steps:
      # checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Script
        run: |
          echo "Processing folder: ${{ matrix.folder }}"
          if [ -f "${{ matrix.folder }}/scripts.sh" ]; then
            bash "${{ matrix.folder }}/scripts.sh"
          else
            echo "No script found in ${{ matrix.folder }}"
          fi

  job3-api:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: [DeterAPI2]
        scripts: [script1.sh,script2.sh,script3.sh]
    
    steps:
      # checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Script
        run: |
          echo "Processing folder: ${{ matrix.folder }}"
          if [ -f "${{ matrix.folder }}/scripts.sh" ]; then
            bash "${{ matrix.folder }}/scripts.sh"
          else
            echo "No script found in ${{ matrix.folder }}"
          fi
